site_name: Shouldly
theme: readthedocs
repo_url: https://github.com/shouldly/shouldly

pages:
- Home: index.md
- Example Classes: exampleClasses.md
- Configuration: configuration.md

- Equality:
  - ShouldBe: assertions/shouldBe.md
  - ShouldNotBe: assertions/shouldNotBe.md
